<?php

return array(
	array(
		'name'          =>  'Events Sidebar',
		'id'            => 'wiloke-events-sidebar',
		'description'   =>  'Widgets in this area will be shown on the Events Page Template',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          =>  'Listing Sidebar',
		'id'            => 'wiloke-listing-sidebar',
		'description'   =>  'Widgets in this area will be shown on Listing Location page, Listing Category page and Listing Template page.',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          =>  'Single Listing Sidebar',
		'id'            => 'wiloke-singular-listing-sidebar',
		'description'   =>  'All widgets in this area will be shown only on the single listing page.',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	),
    array(
        'name'          =>  'Blog Sidebar',
        'id'            => 'wiloke-blog-sidebar',
        'description'   =>  'Widgets in this area will be shown on Blog, Archive, Search and Single page.',
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<h4 class="widget_title">',
        'after_title'   => '</h4>',
    ),
	array(
		'name'          =>  'WooCommerce Sidebar',
		'id'            => 'wiloke-woocommerce-sidebar',
		'description'   =>  'Widgets in this area will be shown on whole WooCommerce pages.',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          =>  'Footer 1',
		'id'            => 'wiloke-footer-1',
		'description'   =>  'We recommend you to use only one widget item for this area',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          =>  'Footer 2',
		'id'            => 'wiloke-footer-2',
		'description'   =>  'We recommend you to use only one widget item for this area',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          =>  'Footer 3',
		'id'            => 'wiloke-footer-3',
		'description'   =>  'We recommend you to use only one widget item for this area',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          =>  'Footer 4',
		'id'            => 'wiloke-footer-4',
		'description'   =>  'We recommend you to use only one widget item for this area',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          =>  'Footer 5',
		'id'            => 'wiloke-footer-5',
		'description'   =>  'We recommend you to use only one widget item for this area',
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget_title">',
		'after_title'   => '</h4>',
	)
);